export const environment = {
    adminLogin:"http://localhost:3000/adminDetails/",
    userLogin:"http://localhost:3000/userProfile/",
    laptopDetails:"http://localhost:3000/laptops/",
    audiDetails:"http://localhost:3000/audio/",
    mobileDetail:"http://localhost:3000/mobile/",
    cartDetails:"http://localhost:3000/cart/",
    mobileIcon:"../../assets//Images/phone.jpg",
    audioIcon:"../../assets//Images/audio.jpg",
    laptopIcon:"../../assets//Images/laptop.jpg",
    oneplusConceptImg:"../assets/Images/images.jfif",
    samsungzflipImg:"../assets/Images/images (1).jfif",
    sonywh1000:"../assets/Images/ANC.jpeg",
    asusLogo:"../../assets//Images/asus.jpg",
    appleLogo:"../../assets//Images/apple.png",
    hpLogo:"../../assets//Images/hp.jpg",
    dellLogo:"../../assets//Images/dell.png",
    acerLogo:"../../assets//Images/acer.png",
    realmeLogo:"../../assets//Images/realme.png",
    ancIcon:"../../assets//Images/ANC.jpeg",
    onearIcon:"../../assets//Images/onear.jpeg",
    inearIcon:"../../assets//Images/inear.jpeg",
    twsIcon:"../../assets//Images/tws.jpeg",
    overearIcon:"../../assets//Images/over-ear.jpeg",
    neckbandIcon:"../../assets//Images/neck-band.jpeg",
    btspeakerIcon:"../../assets//Images/bt-speaker-2.jpeg",
    hometheaterIcon:"../../assets//Images/home-theatre.jpeg",
    offerDate:"Aug 04, 2023 17:28:00",
};
